version: "3.8"

services:
  db:
    image: "postgres:13.4"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:3.2-alpine"
    command: redis-server
    ports:
      - 6379:6379

  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    volumes:
      - .:/myapp
      - gems:/gems
    depends_on:
      - db
      - redis

volumes:
  postgres:
  gems:
