version: "3.8"

services:
  db:
    image: "postgres:13.4"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    command: redis-server
    ports:
      - 6379:6379

  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - gems:/gems
    depends_on:
      - db
      - redis
    env_file:
      - .env

  sidekiq:
    build: .
    command: bash sidekiq_start.sh
    volumes:
      - .:/myapp
      - gems:/gems
    depends_on:
      - app
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres:
  gems:
