default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: zssn_maxihost_api_development

test:
  <<: *default
  database: zssn_maxihost_api_test

production:
  <<: *default
  database: zssn_maxihost_api_production
