default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

auth_default: &auth_default
  <<: *default
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>

development:
  <<: *auth_default
  database: zssn_maxihost_api_development

test:
  <<: *auth_default
  database: zssn_maxihost_api_test

production:
  <<: *default
  database: zssn_maxihost_api_production
  username: zssn_maxihost_api
  password: <%= ENV["ZSSN_MAXIHOST_API_DATABASE_PASSWORD"] %>
